### ISSUE TITLE
assetFS generates an error 

### ISSUE THREAD

**Issue by arnaud-web** [qor/qor-example#129]
Hi, 

I have this stack trace at startup: 

`
WARNING: AssetFS is used before overwrite it!
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc42000e018, 0xc42057fed0, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/qor/assetfs.SetAssetFS(0x6a10390, 0x51294e0)
        /Users/arnaud/go/src/github.com/qor/assetfs/assetfs.go:33 +0xc3
github.com/qor/qor-example/config/bindatafs.init.0()
        /Users/arnaud/go/src/github.com/qor/qor-example/config/bindatafs/bindatafs.go:26 +0x5d
github.com/qor/qor-example/config/bindatafs.init()
        <autogenerated>:1 +0x104
main.init()
        <autogenerated>:1 +0xbb
`

**Comment by cryptix** [comment]
I've also seen this before, it's not super critical unless you compile with bindatafs and can't load templates etc.

I started to convert all the implicit package level `init() {}`s to `Init() error`s and call them manually to get better control over this.

**Comment by turgayozgur** [comment]
Hi,

Reorder qor-example/main.go imports like that:

```go
package main

import "github.com/qor/qor-example/config/bindatafs"

import (
	"context"
	"flag"
        ...
        ...
```
