### ISSUE TITLE
[Refactor branch] frontend 运行有错误

### ISSUE THREAD

**Issue by dfang** [qor/qor-example#163]
有注意到 refactor branch 使用了next.js 来重构前端

但是npm run dev 跑起来了, 打开 localhost:3000

```
invalid json response body at http://localhost:7000/auth/login reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at http://localhost:7000/auth/login reason: Unexpected token < in JSON at position 0
    at /Users/mj/go/src/github.com/qor/qor-example/frontend/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jasonweng** [comment]
这个分支还没有全部完成。暂时没有打算继续做这块。
