### ISSUE TITLE
`go run main.go` fails

### ISSUE THREAD

**Issue by 0pcom** [qor/qor-example#186]
```
[user@linux  ~]$ cd $GOPATH/src/github.com/qor/qor-example
[user@linux  qor-example]$ go run main.go
Failed to find configuration config/application.yml, using example file config/application.example.yml
Failed to find configuration config/smtp.yml, using example file config/smtp.example.yml
Failed to find configuration config/database.yml, using example file config/database.example.yml
WARNING: AssetFS is used before overwrite it!
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x2e, 0x0, 0x0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
github.com/qor/assetfs.SetAssetFS(0x7fdb390e4910, 0x1b6cbc0)
	/home/user/go/src/github.com/qor/assetfs/assetfs.go:33 +0xc5
github.com/qor/qor-example/config/bindatafs.init.0()
	/home/user/go/src/github.com/qor/qor-example/config/bindatafs/bindatafs.go:26 +0x5d
panic: Error 1698: Access denied for user 'root'@'localhost'

goroutine 1 [running]:
github.com/qor/qor-example/config/db.init.0()
	/home/user/go/src/github.com/qor/qor-example/config/db/db.go:49 +0x716
exit status 2
```

I followed the earlier steps in the quickstart. I am using mariadb but I don't think that's the issue.

**Comment by raven-chen** [comment]
Hi @0pcom 

the error message is "panic: Error 1698: Access denied for user 'root'@'localhost'"
check whether your db has this root account and it is accessible to the given database.
