### ISSUE TITLE
Can't Run Demo Code

### ISSUE THREAD

**Issue by pingadi** [qor/qor-example#34]
Steps used:

- `go get -u github.com/qor/qor`
- `go get -u github.com/qor/qor-example`
- create MySQL database
- insert credentials to qor-example/config/database.yml
- insert credentials to qor-example/config/smtp.yml
- `go run db/seeds/main.go` --> **failed**

Error: 
```
# github.com/qor/admin
../admin/searcher.go:194: cannot use int(s.Pagination.PerPage) (type int) as type int64 in argument to db.Limit
../admin/searcher.go:194: cannot use (int(s.Pagination.CurrentPage) - 1) * int(s.Pagination.PerPage) (type int) as type int64 in argument to db.Limit(int(s.Pagination.PerPage)).Offset
```
Try Fixing:
`add casting to int64 on s.Pagination.CurrentPage and s.Pagination.PerPage (line 194)`
- re-run `go run db/seeds/main.go` --> **success**
- `go run main.go` --> **failed**

Error:
```
# github.com/qor/qor-example/config/auth
config/auth/auth.go:35: Auth.LayoutPath undefined (type *authboss.Authboss has no field or method LayoutPath)
config/auth/auth.go:36: Auth.LayoutFuncMaker undefined (type *authboss.Authboss has no field or method LayoutFuncMaker)
```
Try Fixing:
`comment out qor-example/config/auth/auth.go line 35 and 36`
- re-run `go run main.go`

Error:
```
[info] replacing callback `gorm:delete` from /home/ubuntu/qorsdk/src/github.com/qor/publish/publish.go:144
Failed to create unique index for translations key & locale, got: Error 1170: BLOB/TEXT column 'key' used in key specification without a key length

(Error 1170: BLOB/TEXT column 'key' used in key specification without a key length)
[2016-06-16 14:35:50]
[register] Loading
panic: [register] Error Initializing: template: authboss:8: function "t" not defined

goroutine 1 [running]:
github.com/qor/qor-example/config/auth.init.1()
	/home/ubuntu/qorsdk/src/github.com/qor/qor-example/config/auth/auth.go:58 +0x6a9
github.com/qor/qor-example/config/auth.init()
	/home/ubuntu/qorsdk/src/github.com/qor/qor-example/config/auth/session_storer.go:69 +0xd3
github.com/qor/qor-example/config/admin.init()
	/home/ubuntu/qorsdk/src/github.com/qor/qor-example/config/admin/worker.go:133 +0x7b
main.init()
	/home/ubuntu/qorsdk/src/github.com/qor/qor-example/main.go:29 +0x4a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820272f00)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336
exit status 2
```

Anyone can help what I'm missing or what could I do to fix this?

**Comment by jinzhu** [comment]
sorry for the problem, just fixed that, you need to upgrade `gorm`

**Comment by pingadi** [comment]
Still having same problem on:
- go run main.go --> **failed**

Error:
```
# github.com/qor/qor-example/config/auth
config/auth/auth.go:35: Auth.LayoutPath undefined (type *authboss.Authboss has no field or method LayoutPath)
config/auth/auth.go:36: Auth.LayoutFuncMaker undefined (type *authboss.Authboss has no field or method LayoutFuncMaker)
```

Try Fixing:
`comment out qor-example/config/auth/auth.go line 35 and 36`

- re-run go run main.go --> **failed**

Error:
```
[info] replacing callback `gorm:delete` from /home/ubuntu/qorsdk/src/github.com/qor/publish/publish.go:144
Failed to create unique index for translations key & locale, got: Error 1170: BLOB/TEXT column 'key' used in key specification without a key length

(Error 1170: BLOB/TEXT column 'key' used in key specification without a key length)
[2016-06-16 14:35:50]
[register] Loading
panic: [register] Error Initializing: template: authboss:8: function "t" not defined

goroutine 1 [running]:
github.com/qor/qor-example/config/auth.init.1()
    /home/ubuntu/qorsdk/src/github.com/qor/qor-example/config/auth/auth.go:58 +0x6a9
github.com/qor/qor-example/config/auth.init()
    /home/ubuntu/qorsdk/src/github.com/qor/qor-example/config/auth/session_storer.go:69 +0xd3
github.com/qor/qor-example/config/admin.init()
    /home/ubuntu/qorsdk/src/github.com/qor/qor-example/config/admin/worker.go:133 +0x7b
main.init()
    /home/ubuntu/qorsdk/src/github.com/qor/qor-example/main.go:29 +0x4a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820272f00)
    /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:481 +0x336
exit status 2
```

**Comment by jinzhu** [comment]
`qor-example` requires go 1.6+
