### ISSUE TITLE
http: panic serving [::1]:52761: reflect: Call using zero Value argument goroutine 37 [running]:

### ISSUE THREAD

**Issue by KirylKazlovich** [qor/qor-example#61]
I'm trying to register a new user, then receive an email with a link but as soon as link like this one http://localhost:5001/auth/confirm?cnf=5hK8XjphhnRjvoDB9tfVrgho_e35aK8ggNARGbgOovE%3D is opened I'm getting an exception in console. I have put `Printf`s in `./config/auth/db_storer.go` on lines 31 and 32:

```
fmt.Printf("user: %s", user)
fmt.Printf("attr: %s", attr)
```

Logs:

```
Listening on: 5001
user: {{%!s(uint=646) 2017-02-07 13:39:45 +0100 CET 2017-02-07 13:39:45 +0100 CET <nil>} kiryl.kazlovich@gmail.com XXX { %!s(bool=false)}   [] b5oW3No0hOu0yEmLFPXXX== %!s(bool=false)  <nil>}attr: map[gender: confirm_token: confirmed:%!s(bool=true) addresses:[] recover_token: recover_token_expiry:<nil> model:{%!s(uint=646) 2017-02-07 13:39:45 +0100 CET 2017-02-07 13:39:45 +0100 CET <nil>} email:kiryl.kazlovich@gmail.com password:XXX name:<nil> role:]http: panic serving [::1]:52761: reflect: Call using zero Value argument
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc42116e000)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x6c4fe0, 0xc420deb680)
	/usr/local/go/src/runtime/panic.go:458 +0x243
reflect.Value.call(0x6fe4e0, 0xc42034f720, 0x213, 0x7ac0e3, 0x4, 0xc4210494a8, 0x1, 0x1, 0xc4203542c0, 0x13, ...)
	/usr/local/go/src/reflect/value.go:366 +0x1172
reflect.Value.Call(0x6fe4e0, 0xc42034f720, 0x213, 0xc4210494a8, 0x1, 0x1, 0xc42034f720, 0x213, 0x7349c0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc4211735c0, 0x700260, 0xc42034f6c0, 0x1, 0x1, 0x140)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/storer.go:296 +0x720
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc421174d40, 0x19, 0xc4211735c0, 0x6c4fe0, 0xc421049780)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/config/auth/db_storer.go:34 +0x2e2
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0xb2ebd8, 0xc421174d40, 0x19, 0xc4211735c0, 0xc420128501, 0xc421049701)
	<autogenerated>:2 +0x6a
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc4210e6200, 0x7ad6fa, 0x5)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/context.go:109 +0xb3
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confirmHandler(0xc4200deda0, 0xc4210e6200, 0xae7c80, 0xc420bc75f0, 0xc4210620f0, 0xae7600, 0xc421174180)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:199 +0x601
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc4210e6200, 0xae7c80, 0xc420bc75f0, 0xc4210620f0, 0xc4210e6200, 0xc420dea000)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:86 +0x52
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(0xc420420780, 0xc420ad9be0, 0xae7c80, 0xc420bc75f0, 0xc4210620f0)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/router.go:58 +0x113
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHTTP(0xc420ad9c90, 0xae7c80, 0xc420bc75f0, 0xc4210620f0)
	<autogenerated>:124 +0x79
net/http.(*ServeMux).ServeHTTP(0xc420ae08a0, 0xae7c80, 0xc420bc75f0, 0xc4210620f0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.(*ServeMux).ServeHTTP(0xc420ae0870, 0xae7c80, 0xc420bc75f0, 0xc4210620f0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.(*ServeMux).ServeHTTP(0xc420ae0780, 0xae7c80, 0xc420bc75f0, 0xc4210620f0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc420f6fcc0, 0xae7c80, 0xc420bc75f0, 0xc4210620f0)
	/Users/kirylkazlovich/development/go/src/github.com/gorilla/csrf/csrf.go:267 +0x3ba
main.main.func1.1(0xae7c80, 0xc420bc75f0, 0xc4200e2f00)
	/Users/kirylkazlovich/development/go/src/github.com/qor/qor-example/main.go:37 +0x78
net/http.HandlerFunc.ServeHTTP(0xc420a76d80, 0xae7c80, 0xc420bc75f0, 0xc4200e2f00)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420a8a500, 0xae7c80, 0xc420bc75f0, 0xc4200e2f00)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42116e000, 0xae8600, 0xc42114a4c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by KirylKazlovich** [comment]
I have found the issue. There is no validation `v != null` in `vendor/gopkg.in/authboss.v0/storer.go`. I don't also fully understand, why `vendor` folder is used. Shouldn't the project just have a dependency? If it would be the case, there wouldn't be an issue with the `nil`, because the necessary validation is present here: https://github.com/go-authboss/authboss/blob/master/storer.go
