### ISSUE TITLE
New user email confirm throws error

### ISSUE THREAD

**Issue by medyagh** [qor/qor-example#79]
I got this link in my test email to confirm user email

```
http://localhost:7000/auth/confirm?cnf=IErSvqTtOtVo5YnxQKLeoZTfl0y5WMh6XS_maq7MWmo%3D
```
and when I click on it I get this error :

```
go run main.go
Failed to find configuration config/smtp.yml, using example file config/smtp.example.yml
Failed to find configuration config/database.yml, using example file config/database.example.yml
Failed to create unique index for translations key & locale, got: Error 1170: BLOB/TEXT column 'key' used in key specification without a key length

(Error 1170: BLOB/TEXT column 'key' used in key specification without a key length)
[2017-04-28 19:21:09]
[auth]     Loading
[confirm]  Loading
[recover]  Loading
[register] Loading
[warning] duplicated callback `qor_admin:composite_primary_key` from /Users/z001r9y/go/src/github.com/qor/admin/composite_primary_key_callback.go:31
[warning] duplicated callback `qor_admin:composite_primary_key` from /Users/z001r9y/go/src/github.com/qor/admin/composite_primary_key_callback.go:32
[warning] duplicated callback `qor_admin:composite_primary_key` from /Users/z001r9y/go/src/github.com/qor/admin/composite_primary_key_callback.go:32
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> github.com/qor/qor-example/app/controllers.HomeIndex (4 handlers)
[GIN-debug] GET    /products/:code           --> github.com/qor/qor-example/app/controllers.ProductShow (4 handlers)
[GIN-debug] GET    /category/:code           --> github.com/qor/qor-example/app/controllers.CategoryShow (4 handlers)
[GIN-debug] GET    /switch_locale            --> github.com/qor/qor-example/app/controllers.SwitchLocale (4 handlers)
[auth]     Route: /auth/login
[auth]     Route: /auth/logout
[confirm]  Route: /auth/confirm
[recover]  Route: /auth/recover
[recover]  Route: /auth/recover/complete
[register] Route: /auth/register
Listening on: 7000




http: panic serving [::1]:55106: reflect: Call using zero Value argument
goroutine 784 [running]:
net/http.(*conn).serve.func1(0xc4210f9d60)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x1701e80, 0xc421127930)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
reflect.Value.call(0x173eb80, 0xc421146840, 0x213, 0x17f8a90, 0x4, 0xc4210cb600, 0x1, 0x1, 0xc42000e3e8, 0x13, ...)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:366 +0x113d
reflect.Value.Call(0x173eb80, 0xc421146840, 0x213, 0xc4210cb600, 0x1, 0x1, 0xc421146840, 0x213, 0x1778fa0)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:302 +0xa4
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc42115ac00, 0x1740800, 0xc4211467e0, 0x1, 0x0, 0x0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/storer.go:296 +0x6e8
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc421126f41, 0x9, 0xc42115ac00, 0x9, 0xc42115e240)
	/Users/z001r9y/go/src/github.com/qor/qor-example/config/auth/db_storer.go:30 +0x19a
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0x1d4ef78, 0xc421126f41, 0x9, 0xc42115ac00, 0xc42115e2d8, 0xc4210cb801)
	<autogenerated>:2 +0x63
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc420f21b00, 0x17fa0df, 0x5)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/context.go:109 +0x134
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confirmHandler(0xc42022fd60, 0xc420f21b00, 0x1b72740, 0xc421146000, 0xc421144300, 0x1b720c0, 0xc421108fe0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:196 +0x537
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc420f21b00, 0x1b72740, 0xc421146000, 0xc421144300, 0xc420f21b00, 0xc421122900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:86 +0x52
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(0xc4200a8780, 0xc4211248d0, 0x1b72740, 0xc421146000, 0xc421144300)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/router.go:58 +0xee
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHTTP(0xc421124970, 0x1b72740, 0xc421146000, 0xc421144300)
	<autogenerated>:124 +0x74
net/http.(*ServeMux).ServeHTTP(0xc421122930, 0x1b72740, 0xc421146000, 0xc421144300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc421122900, 0x1b72740, 0xc421146000, 0xc421144300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc4211227e0, 0x1b72740, 0xc421146000, 0xc421144300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc4210f9cc0, 0x1b72740, 0xc421146000, 0xc421144300)
	/Users/z001r9y/go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
main.main.func1.1(0x1b72740, 0xc421146000, 0xc420294c00)
	/Users/z001r9y/go/src/github.com/qor/qor-example/main.go:37 +0x73
net/http.HandlerFunc.ServeHTTP(0xc420f2bc00, 0x1b72740, 0xc421146000, 0xc420294c00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc421117340, 0x1b72740, 0xc421146000, 0xc420294c00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4210f9d60, 0x1b73140, 0xc421110bc0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce
http: panic serving [::1]:55107: reflect: Call using zero Value argument
goroutine 785 [running]:
net/http.(*conn).serve.func1(0xc4210f9e00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x1701e80, 0xc421188e10)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
reflect.Value.call(0x173eb80, 0xc421147720, 0x213, 0x17f8a90, 0x4, 0xc4210cb600, 0x1, 0x1, 0xc42000e700, 0x13, ...)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:366 +0x113d
reflect.Value.Call(0x173eb80, 0xc421147720, 0x213, 0xc4210cb600, 0x1, 0x1, 0xc421147720, 0x213, 0x1778fa0)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:302 +0xa4
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc421186ab0, 0x1740800, 0xc4211476c0, 0x1, 0x0, 0x0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/storer.go:296 +0x6e8
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc4211883d1, 0x9, 0xc421186ab0, 0x9, 0xc42115e900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/config/auth/db_storer.go:30 +0x19a
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0x1d4ef78, 0xc4211883d1, 0x9, 0xc421186ab0, 0xc42115e998, 0xc4210cb801)
	<autogenerated>:2 +0x63
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc421162500, 0x17fa0df, 0x5)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/context.go:109 +0x134
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confirmHandler(0xc42022fd60, 0xc421162500, 0x1b72740, 0xc421146ee0, 0xc421144600, 0x1b720c0, 0xc42116e260)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:196 +0x537
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc421162500, 0x1b72740, 0xc421146ee0, 0xc421144600, 0xc421162500, 0xc421122900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:86 +0x52
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(0xc4200a8780, 0xc4211248d0, 0x1b72740, 0xc421146ee0, 0xc421144600)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/router.go:58 +0xee
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHTTP(0xc421124970, 0x1b72740, 0xc421146ee0, 0xc421144600)
	<autogenerated>:124 +0x74
net/http.(*ServeMux).ServeHTTP(0xc421122930, 0x1b72740, 0xc421146ee0, 0xc421144600)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc421122900, 0x1b72740, 0xc421146ee0, 0xc421144600)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc4211227e0, 0x1b72740, 0xc421146ee0, 0xc421144600)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc4210f9cc0, 0x1b72740, 0xc421146ee0, 0xc421144600)
	/Users/z001r9y/go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
main.main.func1.1(0x1b72740, 0xc421146ee0, 0xc421144000)
	/Users/z001r9y/go/src/github.com/qor/qor-example/main.go:37 +0x73
net/http.HandlerFunc.ServeHTTP(0xc420f2bc00, 0x1b72740, 0xc421146ee0, 0xc421144000)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc421117340, 0x1b72740, 0xc421146ee0, 0xc421144000)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4210f9e00, 0x1b73140, 0xc420f217c0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce
http: panic serving [::1]:55108: reflect: Call using zero Value argument
goroutine 818 [running]:
net/http.(*conn).serve.func1(0xc4210f9ea0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x1701e80, 0xc4211ac330)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
reflect.Value.call(0x173eb80, 0xc4211a2680, 0x213, 0x17f8a90, 0x4, 0xc4210cb600, 0x1, 0x1, 0xc42000ebc0, 0x13, ...)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:366 +0x113d
reflect.Value.Call(0x173eb80, 0xc4211a2680, 0x213, 0xc4210cb600, 0x1, 0x1, 0xc4211a2680, 0x213, 0x1778fa0)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:302 +0xa4
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc4211a87e0, 0x1740800, 0xc4211a2620, 0x1, 0x0, 0x0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/storer.go:296 +0x6e8
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc4211898c1, 0x9, 0xc4211a87e0, 0x9, 0xc42115f0d0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/config/auth/db_storer.go:30 +0x19a
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0x1d4ef78, 0xc4211898c1, 0x9, 0xc4211a87e0, 0xc42115f168, 0xc4210cb801)
	<autogenerated>:2 +0x63
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc421162cc0, 0x17fa0df, 0x5)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/context.go:109 +0x134
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confirmHandler(0xc42022fd60, 0xc421162cc0, 0x1b72740, 0xc421147dc0, 0xc421144900, 0x1b720c0, 0xc42116f440)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:196 +0x537
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc421162cc0, 0x1b72740, 0xc421147dc0, 0xc421144900, 0xc421162c00, 0xc421122900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:86 +0x52
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(0xc4200a8780, 0xc4211248d0, 0x1b72740, 0xc421147dc0, 0xc421144900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/router.go:58 +0xee
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHTTP(0xc421124970, 0x1b72740, 0xc421147dc0, 0xc421144900)
	<autogenerated>:124 +0x74
net/http.(*ServeMux).ServeHTTP(0xc421122930, 0x1b72740, 0xc421147dc0, 0xc421144900)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc421122900, 0x1b72740, 0xc421147dc0, 0xc421144900)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc4211227e0, 0x1b72740, 0xc421147dc0, 0xc421144900)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc4210f9cc0, 0x1b72740, 0xc421147dc0, 0xc421144900)
	/Users/z001r9y/go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
main.main.func1.1(0x1b72740, 0xc421147dc0, 0xc421007e00)
	/Users/z001r9y/go/src/github.com/qor/qor-example/main.go:37 +0x73
net/http.HandlerFunc.ServeHTTP(0xc420f2bc00, 0x1b72740, 0xc421147dc0, 0xc421007e00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc421117340, 0x1b72740, 0xc421147dc0, 0xc421007e00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4210f9ea0, 0x1b73140, 0xc42112a540)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce
http: panic serving [::1]:55109: reflect: Call using zero Value argument
goroutine 834 [running]:
net/http.(*conn).serve.func1(0xc420ef8460)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x1701e80, 0xc4211ad780)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
reflect.Value.call(0x173eb80, 0xc4211a3560, 0x213, 0x17f8a90, 0x4, 0xc4210cb600, 0x1, 0x1, 0xc42000ee08, 0x13, ...)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:366 +0x113d
reflect.Value.Call(0x173eb80, 0xc4211a3560, 0x213, 0xc4210cb600, 0x1, 0x1, 0xc4211a3560, 0x213, 0x1778fa0)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:302 +0xa4
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc4211c4570, 0x1740800, 0xc4211a3500, 0x1, 0x0, 0x0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/storer.go:296 +0x6e8
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc4211acde1, 0x9, 0xc4211c4570, 0x9, 0xc42115f680)
	/Users/z001r9y/go/src/github.com/qor/qor-example/config/auth/db_storer.go:30 +0x19a
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0x1d4ef78, 0xc4211acde1, 0x9, 0xc4211c4570, 0xc42115f708, 0xc4210cb801)
	<autogenerated>:2 +0x63
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc4211635c0, 0x17fa0df, 0x5)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/context.go:109 +0x134
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confirmHandler(0xc42022fd60, 0xc4211635c0, 0x1b72740, 0xc4211a2d20, 0xc421144d00, 0x1b720c0, 0xc4211aa660)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:196 +0x537
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc4211635c0, 0x1b72740, 0xc4211a2d20, 0xc421144d00, 0xc421163500, 0xc421122900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:86 +0x52
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(0xc4200a8780, 0xc4211248d0, 0x1b72740, 0xc4211a2d20, 0xc421144d00)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/router.go:58 +0xee
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHTTP(0xc421124970, 0x1b72740, 0xc4211a2d20, 0xc421144d00)
	<autogenerated>:124 +0x74
net/http.(*ServeMux).ServeHTTP(0xc421122930, 0x1b72740, 0xc4211a2d20, 0xc421144d00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc421122900, 0x1b72740, 0xc4211a2d20, 0xc421144d00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc4211227e0, 0x1b72740, 0xc4211a2d20, 0xc421144d00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc4210f9cc0, 0x1b72740, 0xc4211a2d20, 0xc421144d00)
	/Users/z001r9y/go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
main.main.func1.1(0x1b72740, 0xc4211a2d20, 0xc421144a00)
	/Users/z001r9y/go/src/github.com/qor/qor-example/main.go:37 +0x73
net/http.HandlerFunc.ServeHTTP(0xc420f2bc00, 0x1b72740, 0xc4211a2d20, 0xc421144a00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc421117340, 0x1b72740, 0xc4211a2d20, 0xc421144a00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420ef8460, 0x1b73140, 0xc421163340)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce
http: panic serving [::1]:55115: reflect: Call using zero Value argument
goroutine 838 [running]:
net/http.(*conn).serve.func1(0xc420ef8640)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x1701e80, 0xc4211e8c40)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
reflect.Value.call(0x173eb80, 0xc4211e44c0, 0x213, 0x17f8a90, 0x4, 0xc4210cb600, 0x1, 0x1, 0xc42000f050, 0x13, ...)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:366 +0x113d
reflect.Value.Call(0x173eb80, 0xc4211e44c0, 0x213, 0xc4210cb600, 0x1, 0x1, 0xc4211e44c0, 0x213, 0x1778fa0)
	/usr/local/Cellar/go/1.8/libexec/src/reflect/value.go:302 +0xa4
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc4211ea2a0, 0x1740800, 0xc4211e4460, 0x1, 0x0, 0x0)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/storer.go:296 +0x6e8
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc4211e8241, 0x9, 0xc4211ea2a0, 0x9, 0xc42115fe50)
	/Users/z001r9y/go/src/github.com/qor/qor-example/config/auth/db_storer.go:30 +0x19a
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0x1d4ef78, 0xc4211e8241, 0x9, 0xc4211ea2a0, 0xc42115fee8, 0xc4210cb801)
	<autogenerated>:2 +0x63
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc421163ec0, 0x17fa0df, 0x5)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/context.go:109 +0x134
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confirmHandler(0xc42022fd60, 0xc421163ec0, 0x1b72740, 0xc4211a3c00, 0xc421145100, 0x1b720c0, 0xc4211ab820)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:196 +0x537
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc421163ec0, 0x1b72740, 0xc4211a3c00, 0xc421145100, 0xc421163e00, 0xc421122900)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm/confirm.go:86 +0x52
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(0xc4200a8780, 0xc4211248d0, 0x1b72740, 0xc4211a3c00, 0xc421145100)
	/Users/z001r9y/go/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/router.go:58 +0xee
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHTTP(0xc421124970, 0x1b72740, 0xc4211a3c00, 0xc421145100)
	<autogenerated>:124 +0x74
net/http.(*ServeMux).ServeHTTP(0xc421122930, 0x1b72740, 0xc4211a3c00, 0xc421145100)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc421122900, 0x1b72740, 0xc4211a3c00, 0xc421145100)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.(*ServeMux).ServeHTTP(0xc4211227e0, 0x1b72740, 0xc4211a3c00, 0xc421145100)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc4210f9cc0, 0x1b72740, 0xc4211a3c00, 0xc421145100)
	/Users/z001r9y/go/src/github.com/gorilla/csrf/csrf.go:267 +0x32d
main.main.func1.1(0x1b72740, 0xc4211a3c00, 0xc421144e00)
	/Users/z001r9y/go/src/github.com/qor/qor-example/main.go:37 +0x73
net/http.HandlerFunc.ServeHTTP(0xc420f2bc00, 0x1b72740, 0xc4211a3c00, 0xc421144e00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc421117340, 0x1b72740, 0xc4211a3c00, 0xc421144e00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420ef8640, 0x1b73140, 0xc421163c40)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce

```

**Comment by medyagh** [comment]
@jinzhu @binqin could you please take a look ? ^^

**Comment by alexmironof** [comment]
@medyagh Could you try `full_featured_ec` branch?

**Comment by medyagh** [comment]
@alexmironof thanks that branch works. I wanna contribute to this example, should I contribute to this branch ? or is it gonna be merged back to master soon?

**Comment by alexmironof** [comment]
@medyagh actually I don't know :smile:. You can also contribute to this branch, or you can contribute to `master` and then merge `master` into `full_featured_ec`
Better if @jinzhu answer this question :wink:

**Comment by jinzhu** [comment]
It is not going to happen soon, but we would like to work on the full featured qor example based on that branch.

Hopefully we could start that 2 or 3 weeks later.
